import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import "./globals.css";
import Script from "next/script";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import QueryProviders from "@/components/Util/QueryProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="p-20 h-screen">
        <Script
          strategy="beforeInteractive"
          src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_MAP_KEY}`}
        />
        <Script
          strategy="beforeInteractive"
          src={`https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_MAP_KEY}&submodules=geocoder`}
        />
        <QueryProviders>
          <Header />
          {children}
        </QueryProviders>
      </body>
    </html>
  );
}
